services:
  fintrack-backend:
    container_name: fintrack-backend
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - 8001:8001
    env_file: 
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy

  fintrack-webservice:
    container_name: fintrack-webservice
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - 5173:5173
    env_file:
    - .env.docker

  redis:
    image: redis:7.2-alpine
    container_name: fintrack-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./backend/docker/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres:
    image: postgres:17
    container_name: fintrack-postgres
    env_file:
      - ./.env.docker
    restart: "always"
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d finances"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  redis-data: