services:
  fintrack-backend:
    container_name: fintrack-backend
    env_file: 
      - ./.env.docker
    build:
      context: ./backend/
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    env_file:
      - ./.env.docker
    restart: "always"
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d finances"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: