services:
  fintrack-backend:
    container_name: fintrack-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: 
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    env_file:
      - ./.env
    restart: "always"
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: