services:
  fintrack-backend:
    container_name: fintrack-backend
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: 
      - ./.env.docker
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    container_name: fintrack-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
      - ./backend/docker/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres:
    image: postgres:17
    env_file:
      - ./.env.docker
    restart: "always"
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  redis-data: